// Unit tests for the EpubService read/write round-trip.
//
// Verifies that an EPUB generated by the service can be read back, which is
// the code path the ReaderScreen uses.

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:path_provider_platform_interface/path_provider_platform_interface.dart';
import 'package:plugin_platform_interface/plugin_platform_interface.dart';

import 'package:nova_reader/services/epub_service.dart';

/// A fake path_provider that returns a temp directory.
class _FakePathProvider extends PathProviderPlatform
    with MockPlatformInterfaceMixin {
  final Directory _temp;

  _FakePathProvider(this._temp);

  @override
  Future<String?> getApplicationDocumentsPath() async => _temp.path;

  @override
  Future<String?> getApplicationSupportPath() async => _temp.path;

  @override
  Future<String?> getTemporaryPath() async => _temp.path;
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late Directory tempDir;

  setUp(() async {
    tempDir = await Directory.systemTemp.createTemp('nova_epub_test_');
    PathProviderPlatform.instance = _FakePathProvider(tempDir);
  });

  tearDown(() async {
    if (tempDir.existsSync()) {
      tempDir.deleteSync(recursive: true);
    }
  });

  test('generateFromText produces a readable EPUB', () async {
    final service = EpubService();

    final generated = await service.generateFromText(
      title: 'Test Book',
      author: 'Test Author',
      content: 'Chapter 1\nFirst paragraph of the book.\n\n'
          'Chapter 2\nSecond chapter content.',
    );

    expect(generated.filePath, isNotEmpty);
    expect(generated.title, 'Test Book');
    expect(generated.chapterCount, greaterThanOrEqualTo(1));

    // Read it back — this is what the reader does.
    final read = await service.readEpub(generated.filePath);

    expect(read.title, isNotEmpty);
    expect(read.author, isNotEmpty);
    expect(read.chapters, isNotEmpty);
    expect(read.rawContent, isNotEmpty);
  });
}
